spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot-mvc-jpa
    username: postgres
    password: daniel2013
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: never



